project:
  type: website

website:
  title: "slides_in_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  revealjs:
    toc: true
